
CREATE SCHEMA IF NOT EXISTS usuario_db;

USE usuario_db;

CREATE TABLE IF NOT EXISTS users (
    uid UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_phones (
    uid UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    user_uid UUID NOT NULL,
    number VARCHAR(50) NOT NULL,
    city_code VARCHAR(10) NOT NULL,
    country_code VARCHAR(10) NOT NULL,
    FOREIGN KEY (user_uid) REFERENCES users(uid) ON DELETE CASCADE
);

